name: publish-test-pypi

on:
  push:
    branches: [ main, cont_deployment ]
  workflow_dispatch:

jobs:
  unit-test-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
          pip install ruff

      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term --cov-branch
      
      - name: Run ruff formatter
        run: |
          ruff check .

  pypi-test:
    needs: unit-test-pytest
    runs-on: ubuntu-latest
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Build package
        run: hatch build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}